### ISSUE TITLE
Get helper scripts under the bin directory working

### ISSUE THREAD

**Issue by cheempz** [tracelytics/node-traceview#176]
Low priority (so post-GA).

There are some helper scripts for the customer to run their app with our agent, under: https://github.com/tracelytics/node-traceview/tree/master/bin.  Example of how the `node-ao` script is supposed to be used here: http://docs.traceview.solarwinds.com/Instrumentation/nodejs.html#installing-instrumentation

Should remove unsupported options and get working with AO agent.

**Comment by bmacnaughton** [comment]
yep, i've ignored them so far. good catch.

**Comment by cheempz** [comment]
Guh, just realized iw as doing this in the old `tracelytics` GH org.. moved to https://github.com/librato/node-appoptics/issues/30
